# Generated by Django 2.0.13 on 2020-09-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200906_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='previuos_post',
            new_name='previous_post',
        ),
    ]
